---

- name: Create syslog config directory
  command: "mkdir -p {{ syslog_config_dir }}"

- name: syslog location
  file:
    state: directory
    path: "{{ syslog_config_dir }}"
    owner: "root"
    group: "root"
    mode: 0755

- name: Read CA file
  slurp:
    src: "{{ syslog_ca_file }}"
  register: syslog_ca_data

- name: Copy syslog triggers
  template:
    src: syslog_triggers.yml.j2
    dest: "{{ syslog_config_dir }}/syslog_triggers.yml"
    owner: root
    group: root
    mode: 0640

- name: Get trigger SHA sum
  stat:
    checksum_algorithm: sha256
    path: "{{ syslog_config_dir }}/syslog_triggers.yml"
  register: trigger_sha_sum

- name: Copy syslog config
  template:
    src: syslog.yml.j2
    dest: "{{ syslog_config_dir }}/syslog.yml"
    owner: root
    group: root
    mode: 0640

- name: Apply syslog resources
  command: "kubectl apply -f {{ syslog_config_dir }}/syslog_triggers.yml -f {{ syslog_config_dir }}/syslog.yml"

...