name: Latest
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .
